### ISSUE TITLE
IFORM and ISORM example not working

### ISSUE THREAD

**Issue by bkresning** [ahaselsteiner/compute-hdc#7] opened 2020-04-28 00:07 UTC
Hi Andreas,

I have used your ViroCon phyton package, and it seems like this toolbox in Matlab serves similar purposes. Great work, I found your packages useful for my academic work. 

I am wondering about the probabilistic model (PM) generation as input. I have my own datasets and I am looking to generate my own PM. Is there any guidelines for that? 

Thank you.

**Comment by bkresning** [comment] 2020-04-28 00:35
I looked around your page and found another code about ExponentiatedWeibull. I downloaded the package and now it gives the following error:

Undefined operator './' for input arguments of type 'function_handle'.

Error in ExponentiatedWeibull/icdf (line 121)
          x = this.Alpha .* (-1 .* log(1 - p.^(1 ./ this.Delta))).^(1 ./ this.Beta);

Kindly advise, I found your package is very helpful and I am wishing to use them in my academic work. Thank you.

**Comment by ahaselsteiner** [comment] 2020-04-28 09:45
Hi bkresning,

happy to hear that you find ViroCon and this software package useful!

The Matlab software package "compute-hdc" has no functionality for fitting a given probabilistic model structure to a dataset. It is intended only for the next step - if you already have a probabilistic model you can express it using compute-hdc's data structure and compute an environmental contour based on it. Do you already have a probabilistic model (a joint distribution function of some environmental variables)? In that case I am happy to help you to correctly express it in compute-hdc's data structure.

If you don't have the probabilistic model yet, you could either write your own fitting procedure in Matlab or alternatively use our Python package "viroconcom" that provides both, fitting procedures and environmental contour computation (https://github.com/virocon-organization/viroconcom).

Best, Andreas

**Comment by ahaselsteiner** [comment] 2020-04-28 13:22
Hi bkresning again,

I cannot see it in your current post, but as your title tells the example files for the IFORM and ISORM contour were not working. This is fixed now. There was an error in the used syntax of model#9. Also, I added the package exponentiated-weibull as a submodule such that users directly have it. 

These changes have been added to a new release, version 1.2.3.

Thanks for opening the issue!

Did these fixes solve your problem?

**Comment by bkresning** [comment] 2020-04-28 14:07
Hi Andreas,

Regarding the distribution fit, thank you for the clarification. I don't have a probabilistic model yet. I saw on your profile you submitted a paper to OMAE 2020, would you mind sharing the paper (if its published already, of course). Otherwise, I will do some readings to educate myself about joint probability fitting. I also am familiar with ViroCon fitting.

Regarding the update, yes it works smoothly now. The clone/download button does not include the weibull folder but i managed to downloaded it separately. 

Thank you very much for the help.

**Comment by ahaselsteiner** [comment] 2020-04-28 14:47
Sounds good that it works now.
Yes, the submodule is only also downloaded if you use the shell command that I now added to the readme file: git clone --recurse-submodules https://github.com/ahaselsteiner/compute-hdc.git

Yes, I am happy to send you a copy of our OMAE 2020 paper. What's your email address? Feel free to send me an email at a.haselsteiner@uni-bremen.de if you don't want to post it here.

**Comment by bkresning** [comment] 2020-04-28 19:33
Hi Andreas,

Could this package work with Matlab copulafit output? 

I am aware that you provided several examples using weibull/exponentiatedweibull/lognormal, and some of those can be generated with Viroconcom package. I can always try this method.

**Comment by ahaselsteiner** [comment] 2020-04-29 12:47
Unfortunately copulas are not supported in compute-hdc. One can define models only as "global hierarchical models" (some researchers also call working with such models the "conditonal modelling approach"). Viroconcom currently also does not support copulas-based models, however, we plan to implement functionality for them in future (currently, we are not yet working on it, however).

**Comment by ahaselsteiner** [comment] 2020-05-07 17:51
After some email exchanges and creating version 1.2.4 the issue is sovled. I am closing it.

**Closed as completed by ahaselsteiner** 2020-05-07 17:51 UTC

**Comment by BeyondLee518** [comment] 2020-07-23 08:49
Hi Andreas,
Have your IFORM and ISORM considered Rosenblatt Transformation?Do you follow the IFORM described by DNV GL RP205 to implement the code?

**Comment by ahaselsteiner** [comment] 2020-07-23 10:42
Hi BeyondLee,

yes, the IFORM and ISORM implementations use the inverse Rosenblatt transformation. 

About DNV GL's C205: They should refer to the paper of Winterstein et al. (1993), which is what "IFORM contours" are usually meant to be and what is implemented here. To answer more precisely I would need the exact text of guidance you are referring to in the C205.

Best, Andreas

**Comment by BeyondLee518** [comment] 2020-07-23 15:58
Hi Andreas,
Thank you very much!I think I should learn from you!
With regeads,
Lee


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ahaselsteiner/compute-hdc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 晚上6:42
收件人:&nbsp;"ahaselsteiner/compute-hdc"<compute-hdc@noreply.github.com&gt;;
抄送:&nbsp;"2014096383"<2014096383@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ahaselsteiner/compute-hdc] IFORM and ISORM example not working (#7)





 
Hi BeyondLee,
 
yes, the IFORM and ISORM implementations use the inverse Rosenblatt transformation.
 
About DNV GL's C205: They should refer to the paper of Winterstein et al. (1993), which is what "IFORM contours" are usually meant to be and what is implemented here. To answer more precisely I would need the exact text of guidance you are referring to in the C205.
 
Best, Andreas
